### ISSUE TITLE
J14 not co-located with Iridium modem

### ISSUE THREAD

**Issue by MCasari-PMEL** [NOAA-PMEL/EDD-LCP_Control#2]
## Issue

Connector J14 is located on the opposite side of tall components from Iridium Modem.  J14 is the U.fl connector which routes the antenna to the modem, and should be as short as possible.

## Fix

Move J14 to a position directly adjacent to Iridium modem.  Use the modem as a reference for where that signal comes from and how to keep it short.  Also look up preterminated cables to add to BOM, and see standard cut lengths.

**Comment by AlexMTurpin** [comment]
Fixed in newest version
